{
 "title": "Clickhouse",
 "description": "Clickhouse metrics",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(ClickHouseAsyncMetrics_Uptime{job=\"clickhouse-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseMetrics_Query{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_Merge{instance=\"$instance\"}",
     "legendFormat": "merge {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows{instance=\"$instance\"}[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReplicatedChecks{instance=\"$instance\"}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedFetch{instance=\"$instance\"}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedSend{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ClickHouseMetrics_ReadonlyReplica{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_leader_replica{instance=\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes{instance=\"$instance\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_Read{instance=\"$instance\"}"
    },
    {
     "expr": "ClickHouseMetrics_Write{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundPoolTask{instance=\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{instance=\"$instance\"}",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{instance=\"$instance\"}",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection{instance=\"$instance\"}",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheMisses{instance=\"$instance\"}[5m])",
     "legendFormat": "misses {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheHits{instance=\"$instance\"}[5m])",
     "legendFormat": "hits {{job}}"
    }
   ]
  }
 ]
}